name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
 
on:
  push:
    branches:
      - main
      - development  # Wird nur getriggered, wenn Code in "master" gepusht wird
 
jobs:
  CI:
    runs-on: [selfrunner, marcorunner]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
 
      - name: Install Dependencies
        run: npm install

      - name: Build Image
        run: docker build -t helltrap/m324lb01:latest .  

  Deploy:
    runs-on: [selfrunner, marcorunner]
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
 
      - name: Build and Push Docker Image
        run: |
          docker push mtirx/m324lb01:latest
